export const CHECK_ITEM = 'CHECK_ITEM';
export const CHECK_ALL_ITEMS = 'CHECK_ALL_ITEMS';
export const RESET_CHECKED_ITEMS = 'RESET_CHECKED_ITEMS';
export const ASSIGN_CHECKED_ITEMS = 'ASSIGN_CHECKED_ITEMS';
export const SUBMIT_ASSIGNMENTS = 'SUBMIT_ASSIGNMENTS';
