export const EDIT_ASSIGNEE = 'EDIT_ASSIGNEE';
export const CHECK_ITEM = 'CHECK_ITEM';
export const ASSIGN_CHECKED_ITEMS = 'ASSIGN_CHECKED_ITEMS';
export const RESET_ASSIGNMENT = 'RESET_ASSIGNMENT';
export const RESET_ALL = 'RESET_ALL';
export const SUBMIT_ASSIGNMENTS = 'SUBMIT_ASSIGNMENTS';
