export const EDIT_ASSIGNEE = 'EDIT_ASSIGNEE';
export const CHECK_ITEM = 'CHECK_ITEM';
export const ASSIGN_CHECKED_ITEMS = 'ASSIGN_CHECKED_ITEMS';
export const RESET_ASSIGNED_ITEMS = 'RESET_ASSIGNED_ITEMS';
export const SUBMIT_ASSIGNMENTS = 'SUBMIT_ASSIGNMENTS';
